### ISSUE TITLE
OSS remote backend with state-locking: OTSParameterInvalid

### ISSUE THREAD

**Issue by GabrielZabielski** [terraform-providers/terraform-provider-alicloud#1541]
Hello,

When I try to use a state-locking feature of the remote backend, its return below error:
```
Error: Error locking source state: Error acquiring the state lock: 2 errors occurred:
	* OTSParameterInvalid Duplicated attribute column name with primary key column: 'LockID'. 00058fc9-1fc7-02bb-c5d8-970a280c28c8
	* unexpected end of JSON input
```
Additionally, the remote backend, in my case, has never write to the table store. However, the connection to a table store is not a problem, as evidenced I pasted table store response statistics, that I mad using remote backed.

![image](https://user-images.githubusercontent.com/34765951/62826691-0a27b480-bbc0-11e9-86f4-3990bc10973b.png)
The `PutRow` produce only 4XX.

### Terraform Version
Terraform v0.12.6
RAM role - Admin

### Affected Resource(s)
Please list the resources as a list, for example:
- terraform.backend.oss
- alicloud_ots_instance
- alicloud_ots_table

### Expected Behavior
What should have happened?
- In my opinnion, it should work the same as s3 backend.

### Actual Behavior
What actually happened?
- `terraform apply`
```
Acquiring state lock. This may take a few moments...

Error: Error locking state: Error acquiring the state lock: 2 errors occurred:
	* OTSParameterInvalid Duplicated attribute column name with primary key column: 'LockID'. 00058fc9-1fc7-02bb-c5d8-970a280c28c8
	* unexpected end of JSON input
```
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
##### Provisioning of remote backend with stat-locking:
```hcl
resource "alicloud_oss_bucket" "oss" {
  bucket = "random-bucket-name"
}

resource "alicloud_ots_instance" "table-store-instance-for-state-locking" {
  name = "state-locking-random"
  accessed_by = "Any"
}
resource "alicloud_ots_table" "table-for-state-locking" {
  instance_name = alicloud_ots_instance.table-store-instance-for-state-locking.name
  max_version = 1
  table_name = "lock-random"
  time_to_live = -1
  primary_key {
    name = "LockID"
    type = "String"
  }
}
```
##### Remote backend test:
```hcl
terraform {
  backend "oss" {
    bucket = "random-bucket-name"
    prefix   = "path/mystate"
    key   = "version-1.tfstate"
    region = "cn-shanghai"
    tablestore_endpoint = "https://state-locking-random.cn-shanghai.ots.aliyuncs.com" 
    tablestore_table = "lock-random"
    access_key = "top_secret"
    secret_key = "top_secret"
  }
}
resource "alicloud_security_group" "random" {
  name = "random"
}
```
1. `terraform apply` on the provisioning module,
2. `terraform apply` on the remote backend test module.

**Comment by bittopaz** [comment]
I had the same error here, please take a look at this issue.

**Comment by xiaozhu36** [comment]
HI @GabrielZabielski I am sorry for late reply. This issue came from you have created an primary key with `LockID` before init oss backend. When store the state lock, the oss backend will create a primary key name `LockID` automatically and the primary key can not duplicate in one table. So, please remove the primary key and try again.

In addition, I have added some notes in the PR https://github.com/hashicorp/terraform/pull/22821 . Please check it.

**Comment by bittopaz** [comment]
I created a new alicloud_ots_table, without Primary key named "LockID". Then I got terraform crashed..

```
Initializing modules...

Initializing the backend...
Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now check for existing state in the backends.


panic: [tablestore] invalid input

goroutine 1 [running]:
github.com/aliyun/aliyun-tablestore-go-sdk/tablestore.NewPrimaryKeyColumn(0xc0003c1cc0, 0x8, 0x8, 0x2587c80, 0xc0003c1c60, 0x0, 0x0)
	/private/tmp/terraform-20190917-90047-18ajf1n/terraform-0.12.9/pkg/mod/github.com/aliyun/aliyun-tablestore-go-sdk@v4.1.2+incompatible/tablestore/util.go:279 +0x333
github.com/aliyun/aliyun-tablestore-go-sdk/tablestore.(*PrimaryKey).Build(0xc000529e60, 0xc00049c900, 0x183, 0x14, 0xbf589241cee61a28)
	/private/tmp/terraform-20190917-90047-18ajf1n/terraform-0.12.9/pkg/mod/github.com/aliyun/aliyun-tablestore-go-sdk@v4.1.2+incompatible/tablestore/util.go:388 +0x200
github.com/aliyun/aliyun-tablestore-go-sdk/tablestore.(*TableStoreClient).GetRow(0xc00029c230, 0xc00058ec20, 0xc00058ec28, 0x1, 0x1)
	/private/tmp/terraform-20190917-90047-18ajf1n/terraform-0.12.9/pkg/mod/github.com/aliyun/aliyun-tablestore-go-sdk@v4.1.2+incompatible/tablestore/api.go:610 +0xf6
github.com/hashicorp/terraform/backend/remote-state/oss.(*RemoteClient).getMD5(0xc000492e60, 0xc00038c810, 0x0, 0x0, 0xbf58924425eb4e50, 0x67fe718d6)
	/private/tmp/terraform-20190917-90047-18ajf1n/terraform-0.12.9/src/github.com/hashicorp/terraform/backend/remote-state/oss/client.go:237 +0x254
github.com/hashicorp/terraform/backend/remote-state/oss.(*RemoteClient).Get(0xc000492e60, 0xc00058ed58, 0x1, 0x1)
	/private/tmp/terraform-20190917-90047-18ajf1n/terraform-0.12.9/src/github.com/hashicorp/terraform/backend/remote-state/oss/client.go:81 +0x129
github.com/hashicorp/terraform/state/remote.(*State).refreshState(0xc00053e9b0, 0xc0006c1dd0, 0xc00047ef70)
	/private/tmp/terraform-20190917-90047-18ajf1n/terraform-0.12.9/src/github.com/hashicorp/terraform/state/remote/state.go:95 +0x38
github.com/hashicorp/terraform/state/remote.(*State).RefreshState(0xc00053e9b0, 0x0, 0x0)
	/private/tmp/terraform-20190917-90047-18ajf1n/terraform-0.12.9/src/github.com/hashicorp/terraform/state/remote/state.go:88 +0x79
github.com/hashicorp/terraform/command.(*Meta).backendMigrateState_s_s(0xc00044ba40, 0xc00019d2d0, 0x0, 0x0)
	/private/tmp/terraform-20190917-90047-18ajf1n/terraform-0.12.9/src/github.com/hashicorp/terraform/command/meta_backend_migrate.go:280 +0x585
github.com/hashicorp/terraform/command.(*Meta).backendMigrateState(0xc00044ba40, 0xc00019d2d0, 0x0, 0xc00058f300)
	/private/tmp/terraform-20190917-90047-18ajf1n/terraform-0.12.9/src/github.com/hashicorp/terraform/command/meta_backend_migrate.go:104 +0x3a4
github.com/hashicorp/terraform/command.(*Meta).backend_C_r_S_changed(0xc00044ba40, 0xc000562aa0, 0x684cee79, 0xc000363860, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/terraform-20190917-90047-18ajf1n/terraform-0.12.9/src/github.com/hashicorp/terraform/command/meta_backend.go:824 +0x46d
github.com/hashicorp/terraform/command.(*Meta).backendFromConfig(0xc00044ba40, 0xc000209740, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/terraform-20190917-90047-18ajf1n/terraform-0.12.9/src/github.com/hashicorp/terraform/command/meta_backend.go:550 +0x8eb
github.com/hashicorp/terraform/command.(*Meta).Backend(0xc00044ba40, 0xc00058f740, 0x0, 0xc000209700, 0x1, 0x1, 0x0)
	/private/tmp/terraform-20190917-90047-18ajf1n/terraform-0.12.9/src/github.com/hashicorp/terraform/command/meta_backend.go:85 +0x599
github.com/hashicorp/terraform/command.(*InitCommand).initBackend(0xc00044ba40, 0xc0002ac000, 0x296872a, 0xf, 0xc000289e40, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/terraform-20190917-90047-18ajf1n/terraform-0.12.9/src/github.com/hashicorp/terraform/command/init.go:473 +0x1bc
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc00044ba40, 0xc0000bc010, 0x0, 0x0, 0xc00012c7d0)
	/private/tmp/terraform-20190917-90047-18ajf1n/terraform-0.12.9/src/github.com/hashicorp/terraform/command/init.go:287 +0x188d
github.com/mitchellh/cli.(*CLI).Run(0xc000450280, 0xc000450280, 0xc000537cc0, 0x1)
	/private/tmp/terraform-20190917-90047-18ajf1n/terraform-0.12.9/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1da
main.wrappedMain(0x0)
	/private/tmp/terraform-20190917-90047-18ajf1n/terraform-0.12.9/src/github.com/hashicorp/terraform/main.go:235 +0xb7c
main.realMain(0x0)
	/private/tmp/terraform-20190917-90047-18ajf1n/terraform-0.12.9/src/github.com/hashicorp/terraform/main.go:100 +0xb4
main.main()
	/private/tmp/terraform-20190917-90047-18ajf1n/terraform-0.12.9/src/github.com/hashicorp/terraform/main.go:36 +0x3a



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by xiaozhu36** [comment]
HI @bittopaz Can you show me the reproduce template?

**Comment by bittopaz** [comment]
@xiaozhu36 I created tablestore_table manually, and then use it in the terraform config.

Nothing special, just like the examples in the document.

I wonder how you mange to get it work. Thanks

**Comment by GabrielZabielski** [comment]
> HI @GabrielZabielski I am sorry for late reply. This issue came from you have created an primary key with `LockID` before init oss backend. When store the state lock, the oss backend will create a primary key name `LockID` automatically and the primary key can not duplicate in one table. So, please remove the primary key and try again.
> 
> In addition, I have added some notes in the PR [hashicorp/terraform#22821](https://github.com/hashicorp/terraform/pull/22821) . Please check it.

Hello @xiaozhu36, that's ok, it's not critical for me. 
So, if I need to provide the `ots table` by terraform, what primary key should I create?

**Comment by GabrielZabielski** [comment]
In conclusion - `PrimaryKey` `Name` parameter can't be `LockID` - anything else, but not the `LockID` then the remote backend will work with state locking.
