### ISSUE TITLE
Deploying postgres DB failing

### ISSUE THREAD

**Issue by semionshvarts** [terraform-providers/terraform-provider-alicloud#1809]
Hi there,

We have a problem with deploying postgres DB

### Terraform Version
v0.11.11
provider.alicloud v1.59.0

### Affected Resource(s)
Please list the resources as a list, for example:
- "alicloud_db_instance" "postgres"
- "alicloud_db_account" "postgres_account"

### Terraform Configuration Files
```hcl
provider "alicloud" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region = "${var.region}"
}

resource "alicloud_db_instance" "postgres" {
  engine            = "PostgreSQL"
  engine_version    = "10.0"
  instance_type     = "pg.n2.medium.1"
  instance_storage  = "100"
  instance_name     = "test-params"
  zone_id           = "eu-central-1a" 
  vswitch_id        = "${var.vswitch}"
}

//master login credentials
resource "alicloud_db_account" "postgres_account" {
  instance_id       = "${alicloud_db_instance.postgres.id}"
  name              = "${var.name}"
  password          = "${var.password}"
  description       = "The admin credentials used to access the RDS postgres database"
  type              = "Super" 
}
 
```

### Expected Behavior
database + user are created

### Actual Behavior
DB createad but failed on alicloud_db_account.postgres_account with below error:

test-tf git:(master) ✗ terraform apply
alicloud_db_instance.postgres: Refreshing state... (ID: pgm-gw8advpi5qoz1ztld)
alicloud_db_account.postgres_account: Creating...
  description: "" => "The admin credentials used to access the RDS postgres database"
  instance_id: "" => "pgm-gw8advpi5qoz1ztld"
  name:        "" => "mrbean"
  password:    "<sensitive>" => "<sensitive>"
  type:        "" => "Super"
Error applying plan:
 
1 error(s) occurred:
 
* alicloud_db_account.postgres_account: 1 error(s) occurred:
 
* alicloud_db_account.postgres_account: unexpected EOF
 
Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
panic: runtime error: invalid memory address or nil pointer dereference
2019-10-30T17:07:41.841+0200 [DEBUG] plugin.terraform-provider-alicloud_v1.59.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x3b08323]
2019-10-30T17:07:41.841+0200 [DEBUG] plugin.terraform-provider-alicloud_v1.59.0_x4:
2019-10-30T17:07:41.841+0200 [DEBUG] plugin.terraform-provider-alicloud_v1.59.0_x4: goroutine 102 [running]:
2019-10-30T17:07:41.841+0200 [DEBUG] plugin.terraform-provider-alicloud_v1.59.0_x4: github.com/terraform-providers/terraform-provider-alicloud/alicloud.(*RdsService).WaitForAccount(0xc000af1a08, 0xc0004cd420, 0x1b, 0x4b995e1, 0x9, 0x1f4, 0x1b, 0x0)
2019-10-30T17:07:41.841+0200 [DEBUG] plugin.terraform-provider-alicloud_v1.59.0_x4:     /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-alicloud/alicloud/service_alicloud_rds.go:826 +0xc3
2019-10-30T17:07:41.841+0200 [DEBUG] plugin.terraform-provider-alicloud_v1.59.0_x4: github.com/terraform-providers/terraform-provider-alicloud/alicloud.resourceAlicloudDBAccountCreate(0xc000168230, 0x4a13c80, 0xc00000a1e0, 0xc000168230, 0x0)
2019-10-30T17:07:41.841+0200 [DEBUG] plugin.terraform-provider-alicloud_v1.59.0_x4:     /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-alicloud/alicloud/resource_alicloud_db_account.go:126 +0x547
2019-10-30T17:07:41.841+0200 [DEBUG] plugin.terraform-provider-alicloud_v1.59.0_x4: github.com/terraform-providers/terraform-provider-alicloud/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc000290300, 0xc000198280, 0xc0002a0580, 0x4a13c80, 0xc00000a1e0, 0x200000001, 0x4, 0xc00078b760)
2019-10-30T17:07:41.842+0200 [DEBUG] plugin.terraform-provider-alicloud_v1.59.0_x4:     /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-alicloud/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:305 +0x3b4
2019-10-30T17:07:41.842+0200 [DEBUG] plugin.terraform-provider-alicloud_v1.59.0_x4: github.com/terraform-providers/terraform-provider-alicloud/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc000049200, 0xc000198230, 0xc000198280, 0xc0002a0580, 0xc0008d2390, 0x4, 0x4)
2019-10-30T17:07:41.842+0200 [DEBUG] plugin.terraform-provider-alicloud_v1.59.0_x4:     /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-alicloud/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:289 +0x18f
2019-10-30T17:07:41.842+0200 [DEBUG] plugin.terraform-provider-alicloud_v1.59.0_x4: github.com/terraform-providers/terraform-provider-alicloud/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc0009a61c0, 0xc0002a0120, 0xc0008d62c0, 0x0, 0x0)
2019-10-30T17:07:41.842+0200 [DEBUG] plugin.terraform-provider-alicloud_v1.59.0_x4:     /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-alicloud/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:530 +0x57
2019-10-30T17:07:41.842+0200 [DEBUG] plugin.terraform-provider-alicloud_v1.59.0_x4: reflect.Value.call(0xc000186480, 0xc0009ba000, 0x13, 0x4b936ab, 0x4, 0xc00078df18, 0x3, 0x3, 0xc0005c3840, 0xc0002d1ac0, ...)
2019-10-30T17:07:41.842+0200 [DEBUG] plugin.terraform-provider-alicloud_v1.59.0_x4:     /opt/goenv/versions/1.12.6/src/reflect/value.go:447 +0x461
2019-10-30T17:07:41.842+0200 [DEBUG] plugin.terraform-provider-alicloud_v1.59.0_x4: reflect.Value.Call(0xc000186480, 0xc0009ba000, 0x13, 0xc0005b9f18, 0x3, 0x3, 0x3, 0x4fe2300, 0x1e)
2019-10-30T17:07:41.842+0200 [DEBUG] plugin.terraform-provider-alicloud_v1.59.0_x4:     /opt/goenv/versions/1.12.6/src/reflect/value.go:308 +0xa4
2019-10-30T17:07:41.842+0200 [DEBUG] plugin.terraform-provider-alicloud_v1.59.0_x4: net/rpc.(*service).call(0xc0000e6280, 0xc0009b40a0, 0xc0007ce030, 0xc0007ce050, 0xc000650000, 0xc0004ca520, 0x3e52900, 0xc0002a0120, 0x16, 0x3e52940, ...)
2019-10-30T17:07:41.842+0200 [DEBUG] plugin.terraform-provider-alicloud_v1.59.0_x4:     /opt/goenv/versions/1.12.6/src/net/rpc/server.go:384 +0x14e
2019-10-30T17:07:41.842+0200 [DEBUG] plugin.terraform-provider-alicloud_v1.59.0_x4: created by net/rpc.(*Server).ServeCodec
2019-10-30T17:07:41.842+0200 [DEBUG] plugin.terraform-provider-alicloud_v1.59.0_x4:     /opt/goenv/versions/1.12.6/src/net/rpc/server.go:481 +0x42b
2019/10/30 17:07:41 [TRACE] root: eval: *terraform.EvalWriteState
2019/10/30 17:07:41 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2019/10/30 17:07:41 [TRACE] root: eval: *terraform.EvalIf
2019/10/30 17:07:41 [TRACE] root: eval: *terraform.EvalWriteState
2019/10/30 17:07:41 [TRACE] root: eval: *terraform.EvalWriteDiff
2019/10/30 17:07:41 [TRACE] root: eval: *terraform.EvalApplyPost
2019/10/30 17:07:41 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:
 
* alicloud_db_account.postgres_account: unexpected EOF
2019/10/30 17:07:41 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:
 
* alicloud_db_account.postgres_account: unexpected EOF
2019/10/30 17:07:41 [TRACE] [walkApply] Exiting eval tree: alicloud_db_account.postgres_account
2019/10/30 17:07:41 [TRACE] dag/walk: upstream errored, not walking "provider.alicloud (close)"
2019/10/30 17:07:41 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2019/10/30 17:07:41 [TRACE] dag/walk: upstream errored, not walking "root"
2019-10-30T17:07:41.845+0200 [DEBUG] plugin: plugin process exited: path=/Users/i071873/Downloads/eirini_dev/eirini-release/test-tf/.terraform/plugins/darwin_amd64/terraform-provider-alicloud_v1.59.0_x4
2019/10/30 17:07:41 [TRACE] Preserving existing state lineage "7cd38554-99da-467e-be20-2a133d6700ba"
2019/10/30 17:07:41 [TRACE] Preserving existing state lineage "7cd38554-99da-467e-be20-2a133d6700ba"
2019/10/30 17:07:41 [TRACE] Preserving existing state lineage "7cd38554-99da-467e-be20-2a133d6700ba"
2019/10/30 17:07:41 [TRACE] Preserving existing state lineage "7cd38554-99da-467e-be20-2a133d6700ba"
2019/10/30 17:07:41 [DEBUG] plugin: waiting for all plugin processes to complete...
2019-10-30T17:07:41.852+0200 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
 
 
 
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.
 
When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.
 
[1]: https://github.com/hashicorp/terraform/issues
 
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` of provided terraform

**Comment by xiaozhu36** [comment]
HI  @semionshvarts This issue has been fixed by #1812 and next version will contain it.

**Comment by xiaozhu36** [comment]
Hi @semionshvarts The latest release 1.60.0 has fixed this issue. Please check it.

**Comment by xiaozhu36** [comment]
Closed by no reply.

**Comment by nlamirault** [comment]
Hi,
i've got an error with Postgres 9.4 and Provider 1.63 :

```hcl
Terraform will perform the following actions:                                                             
                                                     
  # alicloud_db_account.account_admin will be created
  + resource "alicloud_db_account" "account_admin" {
      + description = "The admin credentials used to access the RDS postgres database"
      + id          = (known after apply)       
      + instance_id = "rm-xxxxxxxxxx"                                                                                                                                                                        
      + name        = "admin" 
      + password    = (sensitive value)            
      + type        = (known after apply)                                                                                                                                                                           
    }                                                                                                     

  # alicloud_db_account_privilege.account_admin_privilege will be created
  + resource "alicloud_db_account_privilege" "account_admin_privilege" {
      + account_name = "admin"                                                                          
      + db_names     = [                                                                                  
          + "db_test",
        ]
      + id           = (known after apply)
      + instance_id  = "rm-xxxxxxxxxxxx"
      + privilege    = "ReadWrite"
    }

  # alicloud_db_database.db_test will be created
  + resource "alicloud_db_database" "db_test" {
      + character_set = "utf8"
      + description   = "Created by terraform"
      + id            = (known after apply)
      + instance_id   = "rm-xxxxxxxxxx"
      + name          = "db_test"
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above. 
  Only 'yes' will be accepted to approve.

  Enter a value: yes

alicloud_db_database.db_test: Creating...
alicloud_db_account.account_admin: Creating...
alicloud_db_account.account_admin: Still creating... [10s elapsed]
alicloud_db_account.account_admin: Creation complete after 11s [id=rm-dj1ilai59c8gvypr9:kzadmin]

Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_db_database.go:79: Resource  CreateDatabase Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:
SDK.ServerError
ErrorCode: InstanceEngineType.NotSupport
Recommend: 
RequestId: 503C2AC5-E6BE-4BAA-831D-0E522FB4D31E
Message: The instance engine and type does not support operations.

  on rds.tf line 50, in resource "alicloud_db_database" "db_test":
  50: resource "alicloud_db_database" "db_test" {


Releasing state lock. This may take a few moments...
```
