### ISSUE TITLE
Terraform crash when I try to create a alicloud_ram_role

### ISSUE THREAD

**Issue by YuanQY** [terraform-providers/terraform-provider-alicloud#2553]
### Terraform Version
0.12.26

provider versions are 1.86.0, 1.84.0

### Affected Resource(s)
Please list the resources as a list, for example:
- alicloud_ram_role

### Panic Output
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1603fd8]

goroutine 229 [running]:
github.com/aliyun/aliyun-oss-go-sdk/oss.Conn.doRequest(0xc00062d900, 0xc000dc5b00, 0xc000dc5b30, 0x1f145b9, 0x3, 0x0, 0xc00079c340, 0x1a, 0xc0006de698, 0x0, ...)
        /opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/aliyun/aliyun-oss-go-sdk@v0.0.0-20190103054945-8205d1f41e70/oss/conn.go:196 +0x128
github.com/aliyun/aliyun-oss-go-sdk/oss.Conn.Do(0xc00062d900, 0xc000dc5b00, 0xc000dc5b30, 0x1f145b9, 0x3, 0xc0007ec440, 0x18, 0x0, 0x0, 0xc000914660, ...)
        /opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/aliyun/aliyun-oss-go-sdk@v0.0.0-20190103054945-8205d1f41e70/oss/conn.go:63 +0x2df
github.com/aliyun/aliyun-oss-go-sdk/oss.Bucket.do(0xc00062d900, 0xc000325c80, 0x0, 0xc0007ec440, 0x18, 0x1f145b9, 0x3, 0x0, 0x0, 0xc000914660, ...)
        /opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/aliyun/aliyun-oss-go-sdk@v0.0.0-20190103054945-8205d1f41e70/oss/bucket.go:938 +0x1c9
github.com/aliyun/aliyun-oss-go-sdk/oss.Bucket.ListObjects(0xc00062d900, 0xc000325c80, 0x0, 0xc0007ec440, 0x18, 0xc000864f40, 0x2, 0x2, 0x0, 0x0, ...)
        /opt/teamcity-agent/work/9e329aa031982669/pkg/mod/github.com/aliyun/aliyun-oss-go-sdk@v0.0.0-20190103054945-8205d1f41e70/oss/bucket.go:497 +0x1bf
github.com/hashicorp/terraform/backend/remote-state/oss.(*Backend).Workspaces(0xc000200d80, 0xc00041bc20, 0x7, 0xc00048f5e0, 0x0, 0x0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/backend/remote-state/oss/backend_state.go:76 +0x1b0
github.com/hashicorp/terraform/backend/remote-state/oss.(*Backend).StateMgr(0xc000200d80, 0x1f196e4, 0x7, 0x9, 0xc0006df1b8, 0x9, 0x2469f00)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/backend/remote-state/oss/backend_state.go:121 +0xc9
github.com/hashicorp/terraform/builtin/providers/terraform.dataSourceRemoteStateRead(0x246a000, 0xc000786290, 0x1bd0d80, 0xc000e91710, 0xc000481220, 0x16, 0xc00047b660, 0x6, 0x0, 0x0, ...)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/builtin/providers/terraform/data_source_state.go:103 +0x53a
github.com/hashicorp/terraform/builtin/providers/terraform.(*Provider).ReadDataSource(0xc00002ad00, 0xc000481220, 0x16, 0x246a000, 0xc000786290, 0x1bd0d80, 0xc000e91710, 0x0, 0x0, 0x0, ...)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/builtin/providers/terraform/provider.go:80 +0x26d
github.com/hashicorp/terraform/terraform.(*EvalReadData).Eval(0xc00063db20, 0x249fe60, 0xc000ab5ee0, 0x2, 0x2, 0x0, 0x0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval_read_data.go:205 +0x16b5
github.com/hashicorp/terraform/terraform.EvalRaw(0x2424a80, 0xc00063db20, 0x249fe60, 0xc000ab5ee0, 0x0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc0003dfd80, 0x249fe60, 0xc000ab5ee0, 0x2, 0x2, 0xf3e5f5, 0x2424920)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:20 +0xfd
github.com/hashicorp/terraform/terraform.EvalRaw(0x2424bc0, 0xc0003dfd80, 0x249fe60, 0xc000ab5ee0, 0x1bc1420, 0x3547784, 0x1b24b60, 0xc000477000)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x131
github.com/hashicorp/terraform/terraform.Eval(0x2424bc0, 0xc0003dfd80, 0x249fe60, 0xc000ab5ee0, 0xc0003dfd80, 0x2424bc0, 0xc0003dfd80, 0x0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/eval.go:35 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x1e64e60, 0xc0007875e8, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/terraform/graph.go:90 +0xf40
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc00047ca80, 0x1e64e60, 0xc0007875e8, 0xc0006f01c0)
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:392 +0x353
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /opt/teamcity-agent/work/9e329aa031982669/src/github.com/hashicorp/terraform/dag/walk.go:314 +0xa9b

### Expected Behavior
Terraform should not crash

### Actual Behavior
Terraform crash.

**Comment by YuanQY** [comment]
I think this is because the bucket name contains spaces (I know this is a mistake of myself, but I think this is an issue).

**Comment by chushenmeshile** [comment]
@YuanQY This is not a defect, the name of a bucket cannot contain spaces
